import Head from 'next/head'
import myMongoConnect from "../components/helpers/mongo-connect";

export default function Home() {
  return (
    <div>
      <Head>
        <title>React traveller app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home page</h1>
    </div>
  )
}

export async function getStaticProps(){
  const {collection,client} = await myMongoConnect('routes');
  const places = await collection.find().toArray();

  client.close();

  return {
    props:{
      places:places.map((place) =>{
        return {
          ...place,
          _id:place._id.toString()
        }
      }),
    },
    revalidate: 60
  }
}